Modify build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -43,6 +43,11 @@ function test {
         exit 2
     fi
 
+    if [[ -z $(which bats) ]]; then
+        echo "Missing bats, which is required for testing."
+        exit 2
+    fi
+    
     bats test/
 }
 
